### ISSUE TITLE
Public URL to Camera works in Desktop browser, but not via mobile (via FB link)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#126]
THis is the link:
http://www.evercam.io/public/cameras/berlin3-evercam

WHen posted on FB and clicked through via android mobile (to FB embedded browser) it gives the message below:

![screenshot_2015-11-28-11-16-28](https://cloud.githubusercontent.com/assets/5648894/11451665/2ccc01ba-95ce-11e5-8391-497ccbac589f.png)

**Comment by affan00** [comment]
@marcoherbst  some browsers doesn't support geolocation. This issue is regarding facebook embedded browser. Facebook use geolocation API in http://touch.facebook.com.  while using facebook on android handset using touch.facebook.com cameras working properly. Either it needs to upgrade to its latest version apps or using through touch.facebook.com. ref link: http://arstechnica.com/business/2010/08/facebook-adds-geolocation-to-iphone-web-apps/

**Comment by affan00** [comment]
@marcoherbst testing on three different android handsets properly working on other browser.

**Comment by marcoherbst** [comment]
That sounds correct. In which case, what is needed is to fail elegantly. The URL should bring you to the camera even if we do not know your location ... after all, it's not necessary to know the user location in order to show the camera.  So, this task is not done. But, if it is too hard for you, then you're welcome to leave it until later.

**Comment by affan00** [comment]
@marcoherbst  issue resolved. Its gives error while unable to retrieve geolocation but bring to camera via fb embedded browser or any other browsers.  
![img-20151214-wa0001](https://cloud.githubusercontent.com/assets/14149453/11776338/14b4d1d2-a268-11e5-82ca-18ff3de6cd8a.jpg)
![img-20151214-wa0000](https://cloud.githubusercontent.com/assets/14149453/11776339/16889714-a268-11e5-8f42-e07cc47e99fe.jpg)

**Comment by affan00** [comment]
Removed geolocation error message and fix issue to bring camera. Deployed changes.
