### ISSUE TITLE
URL Rewrite problem on /public/cameras/{cameras-id}

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site#2]

**Comment by marcoherbst** [comment]
Is this possibly helpful? 
https://www.google.com/webmasters/tools/crawl-url-parameters?hl=en&siteUrl=http://evercam.io/

**Comment by marcoherbst** [comment]
@azharmalik3 , this is the issue, right? You can add more info here?

Also, if you decide, then I am not against migrating all of this to dash.evercam.io (depending on estimated task size)

**Comment by azharmalik3** [comment]
Yes, this is the issue for URL rewrite.

I will add all info later.

**Comment by azharmalik3** [comment]
We are using re-write URL rules for vendors/models / public cameras page. Vendors and models pages rule work fine but cameras single page rule does not work.

Normally, PHP re-write rules are written in `htaccess` file but Bitnami uses `htaccess.conf` file by default instead of ".htaccess" file for security and performance reasons.

Added following rules in `htaccess.config` for single camera but not worked:

```
<Directory "/opt/bitnami/apps/wordpress/htdocs/">
 RewriteEngine On
 RewriteRule "^/?public/cameras/([^/]+)$"  "/public/cameras/index.php?$1"
</Directory>
```

**Comment by marcoherbst** [comment]
moved to Dash
